### ISSUE TITLE
Parametric value 2.99999999999998 is outside of [0, 1] range

### ISSUE THREAD

**Issue by th8m0z** [xvrh/lottie-flutter#143]
This error occurs when using the library to render a JSON Lottie animation.
`flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ParametricCurve.transform
package:flutter/…/animation/curves.dart:37
flutter: #3      Curve.transform
package:flutter/…/animation/curves.dart:92
flutter: #4      BaseKeyframeAnimation.getInterpolatedCurrentKeyframeProgress
package:lottie/…/keyframe/base_keyframe_animation.dart:88
flutter: #5      BaseKeyframeAnimation.value
package:lottie/…/keyframe/base_keyframe_animation.dart:106
flutter: #6      BaseLayer._intersectBoundsWithMask
package:lottie/…/layer/base_layer.dart:281
flutter: #7      BaseLayer.draw
package:lottie/…/layer/base_layer.dart:209
flutter: #8      CompositionLayer.drawLayer
package:lottie/…/layer/composition_layer.dart:104
flutter: #9      BaseLayer.draw
package:lottie/…/layer/base_layer.dart:190
flutter: #10     CompositionLayer.drawLayer
package:lottie/…/layer/composition_layer.dart:104
flutter: #11     BaseLayer.draw
package:lottie/…/layer/base_layer.dart:190
flutter: #12     LottieDrawable.draw
package:lottie/src/lottie_drawable.dart:160
flutter: #13     RenderLottie.paint
package:lottie/src/render_lottie.dart:200
flutter: #14     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2311
flutter: #15     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
flutter: #16     RenderProxyBoxMixin.paint
package:flutter/…/rendering/proxy_box.dart:131
flutter: #17     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2311
flutter: #18     PaintingContext._repaintCompositedChild
package:flutter/…/rendering/object.dart:140
flutter: #19     PaintingContext.repaintCompositedChild
package:flutter/…/rendering/object.dart:100
flutter: #20     PipelineOwner.flushPaint
package:flutter/…/rendering/object.dart:978
flutter: #21     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:438
flutter: #22     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:914
flutter: #23     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:302
flutter: #24     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
flutter: #25     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1055
flutter: #26     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
flutter: #30     _invoke (dart:ui/hooks.dart:251:10)
flutter: #31     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderLottie#5ab88 relayoutBoundary=up2:
flutter:   creator: RawLottie ← AnimatedBuilder ← RepaintBoundary ← Lottie ← FutureBuilder<LottieComposition> ←
flutter:     LottieBuilder ← Stack ← ColoredBox ← Container ← WaitingScreen ← RepaintBoundary ←
flutter:     IndexedSemantics ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=926.0)
flutter:   size: Size(428.0, 428.0)
flutter:   composition:
flutter:     LottieComposition:
flutter:     	Ring Blob Loader_PRECOMP
flutter:     		Parents: Ring Blob Loader_PRECOMP
flutter:     	Ring Blob Loader_PRECOMP
flutter:     		Parents: Ring Blob Loader_PRECOMP
flutter:     	Ring Blob Loader_PRECOMP
flutter:   alignment: center
flutter: This RenderObject has no descendants.
`

**Comment by xvrh** [comment]
Can you share the json file that trigger this error? Thanks.

**Comment by muhammadsaddamnur** [comment]
same issue
